- CMake/AddShader.cmake
add_shader depends on Vulkan::glslc. if not found, guide the user to find vulkan and the executable.
> fix GLSLC-NOTFOUND

- src/ttauri/delayed_format.hpp
- src/ttauri/forward_value.hpp
- src/ttauri/forward_value_tests.cpp
forward_value was not converting `char const * const &` to a `std::string`
> Fix #29 forward_value not working for char pointers

- src/ttauri/datum.hpp
- src/ttauri/datum_tests.cpp
The operator<< and operator>> of the datum_impl class was incorrectly converting lhs to unsigned.
> fix #31 incorrect unsigned shift-left, shift-right

- src/ttauri/GUI/gui_window_vulkan.cpp
- src/ttauri/atomic.hpp
- src/ttauri/counters.hpp
- src/ttauri/logger.hpp
- src/ttauri/random_pcg.hpp
- src/ttauri/sync_clock.hpp
- src/ttauri/system_status.hpp
- src/ttauri/trace.hpp
- src/ttauri/unfair_mutex.hpp
- src/ttauri/unfair_recursive_mutex.hpp
- src/ttauri/wfree_message_queue.hpp
- src/ttauri/wfree_unordered_map.hpp
I was using std::memory_order_* and std::memory_order::memory_order_* values. Change it to use std::memory_order::* instead.
> fix #38 use the modern c++20 std::memory_order

- src/ttauri/GUI/draw_context.hpp
- src/ttauri/stencils/glyph_stencil.cpp
- src/ttauri/stencils/glyph_stencil.hpp
- src/ttauri/stencils/label_stencil.hpp
- src/ttauri/stencils/pixel_map_stencil.cpp
- src/ttauri/stencils/pixel_map_stencil.hpp
- src/ttauri/stencils/stencil.hpp
- src/ttauri/stencils/text_stencil.cpp
- src/ttauri/stencils/text_stencil.hpp
- src/ttauri/widgets/abstract_button_widget.hpp
- src/ttauri/widgets/button_widget.hpp
- src/ttauri/widgets/checkbox_widget.hpp
- src/ttauri/widgets/label_widget.hpp
- src/ttauri/widgets/menu_item_widget.hpp
- src/ttauri/widgets/overlay_view_widget.hpp
- src/ttauri/widgets/radio_button_widget.hpp
- src/ttauri/widgets/scroll_bar_widget.hpp
- src/ttauri/widgets/selection_widget.hpp
- src/ttauri/widgets/text_field_widget.hpp
- src/ttauri/widgets/toggle_widget.hpp
- src/ttauri/widgets/toolbar_tab_button_widget.hpp
- src/ttauri/widgets/toolbar_widget.hpp
- src/ttauri/widgets/widget.cpp
- src/ttauri/widgets/widget.hpp
- src/ttauri/widgets/window_traffic_lights_widget.cpp
Colors are no longer passed through the draw_context, instead they are passed directly in the draw calls.
> closes #4 use colors directly in drawing

- src/ttauri/GUI/draw_context.hpp
- src/ttauri/GUI/pipeline_box_device_shared.cpp
- src/ttauri/GUI/pipeline_box_device_shared.hpp
- src/ttauri/GUI/pipeline_box_vertex.hpp
- src/ttauri/color/sfloat_rgba16.hpp
- src/ttauri/color/sfloat_rgba32.hpp
- src/ttauri/geometry/corner_shapes.hpp
- src/ttauri/version.hpp
- src/ttauri/widgets/button_widget.hpp
- src/ttauri/widgets/checkbox_widget.hpp
- src/ttauri/widgets/menu_item_widget.hpp
- src/ttauri/widgets/overlay_view_widget.hpp
- src/ttauri/widgets/radio_button_widget.hpp
- src/ttauri/widgets/scroll_bar_widget.hpp
- src/ttauri/widgets/selection_widget.hpp
- src/ttauri/widgets/text_field_widget.hpp
- src/ttauri/widgets/toggle_widget.hpp
- src/ttauri/widgets/toolbar_tab_button_widget.hpp
- src/ttauri/widgets/window_traffic_lights_widget.cpp
This is part of the project to remove all state from draw_context and to make widgets draw relative.
> close #48 Remove line_width and corner_shape from draw_context.

- src/ttauri/bezier.hpp
- src/ttauri/bezier_curve.cpp
- src/ttauri/bezier_curve.hpp
- src/ttauri/codec/base_n.hpp
- src/ttauri/graphic_path.cpp
- src/ttauri/version.hpp
- src/ttauri/widgets/toolbar_tab_button_widget.hpp
- fixed some spellings, including method rename `parrallelLine` to `parallelLine` on bezier*
- fixed some spellings
- added missing header
- added missing typename
> small fixes

- README.md
- SPONSORS.md
- docs/BON8.md
- docs/CODE_OF_CONDUCT.md
- docs/CONTRIBUTING.md
- docs/anti_aliasing.md
- docs/code_style.md
- docs/color.md
- docs/dependencies.md
- docs/geometry.md
- docs/gui_system.md
- docs/information_reporting.md
- docs/main_page.md
- docs/preferences.md
- docs/render_architecture.md
- docs/text.md
- docs/themes.md
- docs/time.md
fixed markdown formatting (use # for headings consistently, indentations on lists, newlines after headings)
fixed some spelling issues
> fixed md formatting and spelling [skip ci]

- .github/workflows/build-on-windows.yml
- .github/workflows/cleanup-workflows.yml
- CMakeLists.txt
- tools/CMakeLists.txt
Hey T!
Here are some notes on the PR and it's changes:
- the "cxx_std_20/cxx_std_23 bugfix section" was moved into the MSVC section, because clang-cl doesn't know these compiler flags and stopped configuring
- added a `cleanup-workflows.yml`, which runs scheduled and removes all skip/cancelled/old jobs (there are over 1,3k total jobs now^^ oof, that escalated quickly)
- especially the annoying skipped "Publish PR Test Result" jobs should disapear after merging
- added "Visual Studio 17 2022" (windows-2022 image) to the build matrix, but only for PCH:ON
- i've decided to use `VC16` and `VC17` for a `COMPILER` variable, which replaces the `MSVC19` on artifact filenames and is now also part of the workflow job name
- fixed the Vulkan SDK installation
- they switched their installer type to …
> Some fixes

- CMakeLists.txt
- examples/custom_widgets/CMakeLists.txt
- remove duplicate `include(AddStaticResource)`
- `INSTALL_GMOCK` build option was removed in googletest upstream, it's now `BUILD_GMOCK`
- install `custom_widgets/resources` (mars image was missing after install)
> some_fixes_1

- src/ttauri/GFX/gfx_device_vulkan.cpp
These calls will fail in `RelWithDebugInfo` at `vulkan_funcs.hpp` #12900, 
because you end up in a `#ifndef VULKAN_HPP_DISABLE_ENHANCED_MODE` code block.
I'm not sure, if the debug condition is the correct way to handle this. 
Maybe adding a define before the vulkan header would also fix this issue, e.g.
```
#define VULKAN_HPP_DISABLE_ENHANCED_MODE
#include <vulkan/vulkan.hpp>
```
> wrap *DebugUtilsObjectNameEXT into debug mode condition

- CMakeLists.txt
- CMakeOverride.txt
- CMakePresets.json
- tools/CMakeLists.txt
Changes:
- `CMakeLists.txt`: place gtest lib into folder "extern"
- `tools/CMakeLists.txt`: disable creation of PDB file for Release&RelWithDebugInfo
- `CMakeOverRide.txt`: 
- add reference on the initial issue 
- let RelWithDebugInfo use DEBUG:FASTLINK to speed up linking
- `CMakePresets.json`: fix inheritance and fix using the x86 host by default by setting toolset and host=x64
- this fixes restarting the linker, which formerly resulted in the following message: [build] LINK : the 32-bit linker (C:\...\2022\Preview\VC\Tools\MSVC\1433~1.316\bin\Hostx86\x64\link.exe) failed to do memory mapped file I/O on `hikogui.lib' and is going to restart linking with a 64-bit linker for better throughput
> some cmake tweaks

- .github/workflows/cleanup-workflows.yml
This fixes the "Node.js 12 actions are deprecated" and "set-output" warnings.
> update cleanup-workflows to "actions/github-script@v6"

- .github/workflows/publish-PR-test-results.yml
- update "actions/github-script" to "v6" and use newer API access 
- update "EnricoMi/publish-unit-test-result-action" to "v2" and use newer option: `junit_files`
> fix "Publish PR Test Results"

- examples/hikogui_demo/src/main.cpp
- src/hikogui/char_maps/CMakeLists.txt
- src/hikogui/char_maps/char_converter_tests.cpp
- src/hikogui/char_maps/utf_8.hpp
- src/hikogui/widgets/text_delegate.hpp
Fix #454: Off by one in utf-8 decoder.
> Hebrew character at end of text displayed with replacement-character.

- src/hikogui/GFX/draw_context.hpp
- src/hikogui/GUI/gui_window.cpp
- src/hikogui/widgets/selection_widget.cpp
Fix #456: Added left_to_right() to the draw_context and fix the selection box.
> Fixed: selection box drawing in right-to-left mode.

- .github/workflows/build-on-windows.yml
let's see if this resolves the folder creation issues.
first commit upgrades to `v3.2.3` and primes the cache.
second commit reduced to `v3` and uses the cache.
referencing upstream issue: https://github.com/actions/cache/issues/972
because the tar extraction of the cached file worked with the newer version in my fork,
i closed the upstream issue as resolved.
> updating actions/cache to latest version 3.2.3

- .github/workflows/publish-PR-test-results.yml
i hope this fixes the ['id' not found error](https://github.com/hikogui/hikogui/actions/runs/3981806439/jobs/6825786061#step:3:29). 
sorry, i didn't see that "test_results" != "test-result".
removed debug output via console.log()
json dataset: https://api.github.com/repos/hikogui/hikogui/actions/runs/3979959741/artifacts
(`artifacts.name` needs to equal [artifact upload name](https://github.com/hikogui/hikogui/blob/main/.github/workflows/build-on-windows.yml#L157))
> fix downloading of "test-results" artifact in PRs

- .vscode/extensions.json
- .vscode/settings.json
- docs/build_with_visual_studio_code.md
This adds `.vscode\extensions.json`, which contains a list of recommended extensions for Visual Studio Code (VSCode). It also includes the addition of `"extensions.ignoreRecommendations"` to `.vscode\settings.json` with the default setting of true (ignore) to prevent notifications during development.
Lastly, the documentation has been updated to instruct users of the library to utilize .vsconfig for configuring Microsoft Visual Studio (MSVC) and enabling recommendations in VSCode.
> setup vscode extension recommendations

- .github/workflows/build-on-windows.yml
- CHANGELOG.md
- CMake/CPUID.cmake
- CMakePresets.json
- docs/release_checklist.md
- enable code-coverage steps on CI
- fix links for v0.8.0 in Changelog.md and add reminder to release_checklist.md
- remove "-x64" from displayNames (displayed is now only COMPILER-BUILDTYPE)
- add condition check for env var CI to CI presets, so that they are now automatically hidden on non-CI systems
- changed from CMAKE_INSTALL_PREFIX to installDir on CI presets
- add condition to show the windows presets only on windows = hide windows presets on linux
- removed CMAKE_C_COMPILER_LAUNCHER and CMAKE_C_COMPILER directives, both trigger unused CMAKE directive warning
- renamed the MSVC clang targets to "clangcl" to make room for LLVM clang
- fixed compilation of CPUINFO.cmake with Clang17
> fixed changelog, enabled coverage, tweaked presets

- src/hikogui/widgets/overlay_widget.hpp
- src/hikogui/widgets/selection_delegate.hpp
- src/hikogui/widgets/selection_widget.hpp
This patch fixes two bugs.
The event for button-up was not handled by the scroll-bar and instead was chained to the ancestor the selection button which closed the selection box in response.
This was solved by shortcutting any events in the overlay widget, so that no events would go deeper.
The buttons where parented on the selection-widget instead of the grid-widget that was holding those buttons.
Changed the selection-delegate to accept a parent for the widgets, so that the grid-widget now can become the parent. This solved a lot of weird issues with the selection buttons.
> fix selection box
